# Numpy 

In [1]:
import numpy as np 

In [3]:
a = [1,2,3,4,5]
np_arr = np.array(a)
ans = np_arr**2
print(ans)

[ 1  4  9 16 25]


In [4]:
l = range(10000)

In [5]:
%timeit [i**2 for i in l] # to calculate the time to perform the operation

742 μs ± 82.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
l_np = np.arange(10000) #define the range of numpy array
len(l_np)

10000

In [10]:
%timeit l_np ** 2 # too fast

6.81 μs ± 536 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
a = np.array([1,2,3,4,5])
print(a*2)
print(a.ndim) # know the dimension

[ 2  4  6  8 10]
1


In [17]:
# no of element across each dimension
print(a.shape)

(5,)


In [18]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim,a.shape)

1 (8,)


In [19]:
b = np.arange(1,10,2) # numpy array creation
print(b)

[1 3 5 7 9]


In [20]:
b = np.arange(1,10,0.8) # decimal only allowed in arange not in range
print(b)

[1.  1.8 2.6 3.4 4.2 5.  5.8 6.6 7.4 8.2 9.  9.8]


In [22]:
np.linspace(0,100,12) # 0 se 100 range me kaha par flag lagenge taki 12 flag lag jaye and end point inclusive

array([  0.        ,   9.09090909,  18.18181818,  27.27272727,
        36.36363636,  45.45454545,  54.54545455,  63.63636364,
        72.72727273,  81.81818182,  90.90909091, 100.        ])

In [24]:
type(b)

numpy.ndarray

* Numpy array store same type of data 
* it is Homogeneous
* Numpy array use c language behind the scene so they have a range 

In [32]:
arr1 = np.array([1,2,3,4.0]) # type coercion int convert to float to prevent from data loss
arr2 = np.array([1,2,3,4.0],dtype="long")
arr3 = np.array([1,2,3,"AJ"],dtype="<U32")
print(arr2)
print(arr3)

[1 2 3 4]
['1' '2' '3' 'AJ']


# Working with 2D array

In [36]:
m1 = np.array([[1,2,3],[1,2,3]])
print(m1)
print(len(m1)) # no of rows
print(m1.ndim) # know the dimension
print(m1.shape) # (no of element in row,no of element in col)

[[1 2 3]
 [1 2 3]]
2
2
(2, 3)


In [37]:
a = np.array([1,2,3,4,5],ndmin=2)  # convert the one d array in 2 d array
print(a)

[[1 2 3 4 5]]


In [42]:
arr = np.arange(1,13)
print(arr)
print(arr.shape)

brr = arr.reshape(3,4) # 3 row and 4 col
print(brr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
arr = np.arange(4)
brr = np.resize(arr,(2,4))
print(brr)

[[0 1 2 3]
 [0 1 2 3]]


In [51]:
arr = np.arange(4)
arr.resize((2,4))
print(arr)

[[0 1 2 3]
 [0 0 0 0]]


In [54]:
arr = np.arange(4)
crr = arr
# arr.resize((2,4)) # this is not possible because arr refernce to crr and while referencing resize not work
arr.resize((2,4)) # use refcheck=Flase to run
print(crr)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [57]:
a = np.arange(3).reshape(1,3)
print(a)
print(a.T) # transpose
b = np.arange(3)
print(b.T) # not change no error 

[[0 1 2]]
[[0]
 [1]
 [2]]
[0 1 2]


In [58]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [63]:
c = a.flatten() # two d to one d
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [62]:
b = a.reshape(12) # two d to one d
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [65]:
d = a.reshape(6,-1) #-1 is use to figure it out auto but for 1 dimension only 
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [75]:
# 0 matrix
z = np.zeros(5)
print(z)
# 1 matrix
o = np.ones(5)
print(o)
# 5 matrix
f = np.ones((2,5))*5 
print(f)
# diag matrix
d = np.diag([1,2,3,4,5])
print(d)
# one d array
b = np.diag(d)
print(b)
# 1 in diagonal
i = np.identity(5)
print(i)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
[1 2 3 4 5]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [79]:
m1 = np.arange(1,10).reshape((3,3))
print(m1)
print(m1[1][2]) # dont use it
print(m1[1,2]) # [row,col]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
6


In [85]:
m1 = np.array([100,200,300,400,500])
print(m1[[2,3,1,4]])

[300 400 200 500]


In [87]:
m1 = np.arange(1,10).reshape((3,3))
print(m1)
m1[[0,0,1],[1,2,1]]  #(0,1) (0,2) (1,1)
m1[0,1:3] # 0th row me 1 se 3 excluded


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 3])

In [92]:
ml = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11]])

ml[0:3,2:4]
# or 
ml[:,2:] 

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [93]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [94]:
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [96]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[2:] = b[::-1]
print(a)

[1 2 6 7 8]


In [98]:
m1 = np.arange(12).reshape((3,4))
ml
m1<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [99]:
ml[ml<6]

array([0, 1, 2, 3, 4, 5])

In [100]:
ml[ml%2==0]

array([ 0,  2,  4,  6,  8, 10])

In [101]:
a = np.arange(11)
#divisible by 2 or 5
a[(a%2==0) | (a%5==0)]

array([ 0,  2,  4,  5,  6,  8, 10])

In [103]:
a = np.arange(6)
mask = a%2==0
print(mask)
a[mask] = -1
print(a)

[ True False  True False  True False]
[-1  1 -1  3 -1  5]


In [104]:
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a*b)

[1 4 9]
